Riot-Tech/JobTracker

client/package-lock.json, client/package.json
Bueno gente primer commit para ir dandole forma a las carpetas. En este caso client. Acepten
=> feat(client): new technologies installed

server/package.json, server/prisma/schema.prisma
Se creo el schema de prisma con las tablas basicas que se necesitan.
=> feat(prisma): created prisma schema

server/prisma/schema.prisma
Se agrego la tabla Link y se asocio a los distintos modelos que ya existian.
Ademas se agrego el atributo enabled para preparar el borrado logico.
=> feat(prisma): completed models

client/package.json, client/src/App.tsx, client/src/main.tsx, client/src/redux/hooks.ts, client/src/redux/slices/example.slice.ts, client/src/redux/slices/index.ts, client/src/redux/store.ts
Se creo el store, provider, reducer (a modo de ejemplo) y configuracion basica de redux con TS.
Se reemplazaron algunas dependencias deprecadas para el uso actual de redux.
=> feat(redux): created base redux config, store and reducer

client/src/App.tsx, client/src/pages/Applications.tsx, client/src/pages/Login.tsx, client/src/pages/Profile.tsx, client/src/pages/RootRouter.tsx, client/src/pages/SignUp.tsx, client/src/pages/Spontaneous.tsx, client/vite.config.ts
Se creo la config basica de Routing usando react-router-dom. Se añaden algunas pages para testear la navegacion.
Se corrigio el puerto por defecto para que el front siempre levante en el 3000.
=> feat(routing): created general routing config and pages

server/src/controllers/postUserController.ts, server/src/handlers/getUserByIdHandler.ts, server/src/handlers/postUserHandler.ts, server/src/helpers/postUserHelper.ts, server/src/types.ts
El archivo types agregado para empezar a crear tipos.
=> fix(types/UserRoutes): added types file, and improved errors management

server/src/controllers/index.ts, server/src/controllers/postApplicationController.ts, server/src/handlers/index.ts, server/src/handlers/postApplicationHandler.ts, server/src/helpers/index.ts, server/src/helpers/postApplicationHelper.ts, server/src/routes/applicationRouter.ts, server/src/routes/index.ts, server/src/types.ts
se crearon las rutas para poder postear una Application y sus respectivos controllers, etc..
=> Post application routes, helpers, handlers and controllers

server/src/controllers/postApplicationController.ts, server/src/controllers/postUserController.ts, server/src/handlers/postUserHandler.ts, server/src/helpers/postApplicationHelper.ts, server/src/helpers/postUserHelper.ts, server/src/types.ts
Ya quedo funcionando las rutas para crear una aplicacion laboral nueva y se modificaron los types, ahora no funciona mas con el archivo "types" sino que importamos los modelos directamente desde prisma.
=> fix(postApplication): create new application and prisma types

server/src/controllers/getApplicationController.ts, server/src/controllers/index.ts, server/src/handlers/getApplicationHandler.ts, server/src/handlers/index.ts, server/src/helpers/getApplicationHelper.ts, server/src/helpers/index.ts, server/src/routes/applicationRouter.ts
Se crearon las rutas para poder hacer una peticion de todas las aplicaciones que se hayan realizado por el usuario
=> feat(getApplications): new route, handler, helper and controller

server/src/controllers/index.ts, server/src/controllers/postSpontaneusController.ts, server/src/handlers/index.ts, server/src/handlers/postSpontaneusHandler.ts, server/src/helpers/index.ts, server/src/helpers/postSpontaneousHelper.ts, server/src/routes/index.ts, server/src/routes/spontaneusRouter.ts
se cambiaron los modelos (reiniciar la base de datos) Y se agreg[o la ruta post spontaneous
=> feat(spontaneousPost-prisma.schema): post spontaneous application already function ing

server/src/controllers/disableApplicationController.ts, server/src/controllers/index.ts, server/src/handlers/index.ts, server/src/handlers/updateApplicationHandler.ts, server/src/helpers/disableApplicationHelper.ts, server/src/helpers/index.ts, server/src/routes/applicationRouter.ts
El usuario ya puede deshabilitar una aplicación, quedaron todas las rutas creadas
=> feat(disableApplication): routes, controllers, handlers and helpers.

client/package.json, client/src/App.css, client/src/App.tsx, client/src/components/Logout.tsx, client/src/guard/auth.guard.tsx, client/src/models/interfaces.ts, client/src/models/routes.ts, client/src/pages/Home.tsx, client/src/pages/Login.tsx, client/src/redux/slices/auth.slice.ts, client/src/redux/store.ts, server/src/handlers/authenthicationHandler.ts
basicamente hay rutas publicas como login y sign up en las que un usuario NO logeado puede ingresar, para ingresar a las rutas privadas como Applications por ejemplo, dentro del local storage tiene que tener almacenado el usuario activo y su TOKEN, caso contrario redirige al login, hay persistencia, si haces F5 mantiene el logeo del usuario
=> feat(login-redux-App-Guard): private and public routes added, guard for auth, login working

server/prisma/migrations/20231013200344_/migration.sql, server/src/controllers/disableApplicationController.ts, server/src/controllers/disableSpontaneousController.ts, server/src/controllers/index.ts, server/src/controllers/updateSpontaneousController.ts, server/src/handlers/authenthicationHandler.ts, server/src/handlers/disableApplicationHandler.ts, server/src/handlers/disableSpontaneousHandler.ts, server/src/handlers/index.ts, server/src/handlers/updateApplicationHandler.ts, server/src/handlers/updateSpontaneousHandler.ts, server/src/helpers/disableSpontaneousHelper.ts, server/src/helpers/index.ts, server/src/helpers/updateSpontaneousHelper.ts, server/src/routes/applicationRouter.ts, server/src/routes/spontaneousRouter.ts
El usuario puede editar o deshabilitar una aplicacion o una aplicacion espontanea.
=> Update and Disable applications and spontaneous application

server/prisma/migrations/20231013144929_login_migration/migration.sql, server/src/controllers/disableApplicationController.ts, server/src/controllers/disableSpontaneousController.ts, server/src/controllers/getUserByIdController.ts, server/src/controllers/postApplicationController.ts, server/src/controllers/postSpontaneousController.ts, server/src/controllers/postUserController.ts, server/src/controllers/updateApplicationController.ts, server/src/controllers/updateSpontaneousController.ts, server/src/handlers/disableApplicationHandler.ts, server/src/handlers/disableSpontaneousHandler.ts, server/src/handlers/getApplicationsHandler.ts, server/src/handlers/getUserByIdHandler.ts, server/src/handlers/postApplicationHandler.ts, server/src/handlers/postSpontaneousHandler.ts, server/src/handlers/postUserHandler.ts, server/src/handlers/updateApplicationHandler.ts, server/src/handlers/updateSpontaneousHandler.ts, server/src/helpers/postUserHelper.ts
El servidor ya esta preparado para devolver mensajes especificos para cada caso si los valores que entran son incorrectos o no se ajustan al modeolo
=> Backend validations

server/src/controllers/ApplicationControllers/disableApplicationController.ts, server/src/controllers/ApplicationControllers/getApplicationByIdController.ts, server/src/controllers/ApplicationControllers/getApplicationsController.ts, server/src/controllers/ApplicationControllers/postApplicationController.ts, server/src/controllers/ApplicationControllers/updateApplicationController.ts, server/src/controllers/LinkControllers/disableLinkController.ts, server/src/controllers/LinkControllers/getLinksController.ts, server/src/controllers/LinkControllers/postLinkController.ts, server/src/controllers/LinkControllers/updateLinkController.ts, server/src/controllers/SpontaneousControllers/disableSpontaneousController.ts, server/src/controllers/SpontaneousControllers/getSpontaneousByIdController.ts, server/src/controllers/SpontaneousControllers/getSpontaneousController.ts, server/src/controllers/SpontaneousControllers/postSpontaneousController.ts, server/src/controllers/SpontaneousControllers/updateSpontaneousController.ts, server/src/controllers/UserControllers/getUserByIdController.ts, server/src/controllers/UserControllers/postUserController.ts, server/src/controllers/UserControllers/updateUserController.ts, server/src/handlers/ApplicationHandles/getApplicationByIdHandler.ts, server/src/handlers/ApplicationHandles/getApplicationsHandler.ts, server/src/handlers/SpontaneousHandles/getSpontaneousHandler.ts, server/src/helpers/ApplicationHelpers/getApplicationsHelper.ts, server/src/helpers/SpontaneousHelpers/getSpontaneousHelper.ts, server/src/routes/applicationRouter.ts, server/src/routes/spontaneousRouter.ts
Se agrego el id en la ruta de getAllApplication y getAllSpontaneous para que traiga todas pero unicamente de ese usuario.
=> fix(Application/Spontaneous):added user ID for searching all applications and spontaneous app.

server/src/controllers/ApplicationControllers/disableApplicationController.ts, server/src/controllers/ApplicationControllers/postApplicationController.ts, server/src/controllers/ApplicationControllers/updateApplicationController.ts, server/src/controllers/LinkControllers/disableLinkController.ts, server/src/controllers/LinkControllers/postLinkController.ts, server/src/controllers/LinkControllers/updateLinkController.ts, server/src/controllers/SpontaneousControllers/disableSpontaneousController.ts, server/src/controllers/SpontaneousControllers/getSpontaneousByIdController.ts, server/src/controllers/SpontaneousControllers/postSpontaneousController.ts, server/src/controllers/SpontaneousControllers/updateSpontaneousController.ts, server/src/controllers/UserControllers/updateUserController.ts
Se agregaron las validaciones en los controllers de la ruta link
=> feat(Link):Information validations added

server/src/handlers/ApplicationHandlers/disableApplicationHandler.ts, server/src/handlers/ApplicationHandlers/getApplicationsHandler.ts, server/src/routes/applicationRouter.ts
Se cambio en el Application handler la manera de recibir el id, ahora se envia por query.
=> update(Application.router):Updated data input method for the handler

server/src/controllers/ApplicationControllers/postApplicationController.ts, server/src/controllers/SpontaneousControllers/postSpontaneousController.ts, server/src/handlers/ApplicationHandlers/disableApplicationHandler.ts, server/src/handlers/SpontaneousHandlers/getSpontaneousByIdHandler.ts, server/src/handlers/SpontaneousHandlers/getSpontaneousHandler.ts, server/src/routes/spontaneousRouter.ts
Se cambiaron las validaciones de los links por que generaban conflicto en los controllers y se cambio la manera de recibir la informacion del Front en los handlers
=> fix(Controllers/Handlers):fixed some validations and updated data input methods

client/src/modals/CreateFile.tsx
Se agregaron los estilos al modal
=> feat(createFileModal): styled modal

server/src/app/app.ts, server/src/controllers/FileControllers/postFileController.ts, server/src/utils/cloudUtils.ts
Ahora se crean buckets en Google Cloud para cada usuario, y se suben los archivos alli.
Se borro codigo innecesario en app.ts
=> feat(cloudStorage): created personalised buckets

client/src/models/interfaces.ts, client/src/pages/Profile.tsx, client/src/utils/utilities.ts, client/src/utils/validateCreateSpontaneous.ts, client/src/utils/validateProfileLinks.ts, server/src/controllers/UserControllers/updateUserController.ts, server/src/helpers/UserHelpers/updateUserHelper.ts
Se solucionaron los problemas de los inputs que se despachaban y la actualizacion de la base de datos, solo queda solucionar la persistencia de los estados.
=> fix(profile):changed inputs and validation

client/src/pages/Profile.tsx
Se agregaron estilos a la view de Profile
=> update(profile):added style

client/src/components/EachFile.tsx, client/src/pages/Files.tsx, server/src/helpers/FileHelpers/disableFileHelper.ts, server/src/routes/fileRouter.ts
Se cambiaron los estilos dentro del componente Files, se modificaron los botones y se acomodo el icono para eliminar
=> update(styles):added new styles

client/src/components/EachFile.tsx, server/src/helpers/FileHelpers/disableFileHelper.ts, server/src/utils/cloudUtils.ts
Se soluciono que se puedan eliminar Files tanto en base de datos como en Google Cloud, ahora no vamos a tener mas el problema de eliminar un archivo y que cuando volvamos a cargarlo nos diga que ya existe.
=> fix(Files):fixed delete file in Google Cloud

client/src/components/Spont.tsx, client/src/modals/CreateApplication.tsx, client/src/modals/CreateSpont.module.css, client/src/modals/CreateSpontaneous.tsx
Se cambiaron los estilos del responsive de los modales en App y en Spont
=> style(Spont,App): responsive design

client/src/components/SignUp.tsx, client/src/modals/CreateApplication.tsx, client/src/modals/CreateSpont.module.css, client/src/modals/CreateSpontaneous.tsx, client/src/modals/DownloadFileSuccess.tsx, client/src/modals/EditSpontaneous.tsx, client/src/modals/SignUpSuccess.tsx, client/src/models/interfaces.ts, client/src/pages/Profile.tsx, client/src/utils/validateSignUpForm.ts, server/src/handlers/SignUpHandlers/signUpHandler.ts
Se cambiaron algunos estilos del responsive en varios archivos.
*** En esta version queda comentado el envio de mail.
=> style(multiple filess): Improve responsiveness
